language: node_js
node_js:
  - "5.0.0"
before_script:
  - npm install -g bower karma-cli jshint gulp
  - bower install
script:
  - gulp test
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
